#
# This test file has been generated by kwb.test::create_test_files()
# launched by user micha on 2020-06-03 23:21:51.
# Your are strongly encouraged to modify the dummy functions
# so that real cases are tested. You should then delete this comment.
#

test_that("nextcloud_request() works", {

  expect_error(
    kwb.nextcloud:::nextcloud_request()
    # Objekt 'nextcloud_request' nicht gefunden
  )

})

